version: "3.8"

services:
  app:
    container_name: fitness_wearable_app
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./Laravel/:/var/www/html
      - vendor-volumes:/var/www/html/vendor
    expose:
      - "9000"

  nginx:
    image: nginx
    container_name: fitness_wearable_nginx
    ports:
      - 18000:80
    volumes:
      - ./Laravel/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
    depends_on:
      - app
      - nextjs

  db:
    image: mysql:8.3
    container_name: fitness_wearable_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitness_wearable
      MYSQL_USER: fitness_wearable_user
      MYSQL_PASSWORD: aug8308g
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 13306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fitness_wearable_phpmyadmin
    environment:
      PMA_HOST: fitness_wearable_db
      PMA_PORT: 13306
    ports:
      - "18080:80"
    depends_on:
      - db

  nextjs:
    build:
      context: ./docker/nextjs
      dockerfile: Dockerfile
    container_name: fitness_wearable_nextjs
    image: node:22
    volumes:
      - ./Nextjs:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
    ports:
      - 13000:3000
    depends_on:
      - app
      - db

volumes:
  vendor-volumes:
