version: "3.8"

services:
  app:
    container_name: #設定
    build: ./docker/php
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx
    container_name: #設定
    build: ./docker/nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
    depends_on:
      - app

  db:
    image: mysql:8.4
    container_name: #設定
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: #設定
      MYSQL_USER: #設定
      MYSQL_PASSWORD: #設定
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: #設定
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M
    ports:
      - "8080:80"
    depends_on:
      - db